### ISSUE TITLE
Some PDFs can't be archived

### ISSUE THREAD

**Issue by symroe** [DemocracyClub/EveryElection#978] opened 2021-01-29 14:27 UTC
If a PDF can't be accessed when creating an ID, a 500 is raised to the user.

We should catch this error and deal with it better, but also try to work out why the PDF can't be accesses in the first place. This might be some sort of anti-hotlinking script that we could bypass by passing some real-looking headers.

https://sentry.io/organizations/democracy-club-gp/issues/2186812617/?referrer=github_plugin

```
HTTPError: HTTP Error 403: Forbidden
(9 additional frame(s) were not displayed)
...
  File "elections/views/general.py", line 132, in post
    doc.archive_document(document_url, kwargs["election_id"])
  File "elections/models.py", line 465, in archive_document
    urllib.request.urlretrieve(url, tmp.name)

HTTPError: HTTP Error 403: Forbidden
```

**Comment by chris48s** [comment] 2021-01-30 16:46
dupe of https://github.com/DemocracyClub/EveryElection/issues/66 - more discussion there

**Closed** 2021-02-01 11:01 UTC
